// <auto-generated />
using AdopcionMascotas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdopcionMascotas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdopcionMascotas.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Perro juguetón y sociable",
                            Edad = 3,
                            Especie = 1,
                            Estado = 0,
                            Imagen = "/images/placeholder.jpg",
                            Nombre = "Firulais"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Perra tranquila y cariñosa",
                            Edad = 5,
                            Especie = 1,
                            Estado = 0,
                            Imagen = "/images/placeholder.jpg",
                            Nombre = "Luna"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Gato curioso y activo",
                            Edad = 2,
                            Especie = 2,
                            Estado = 0,
                            Imagen = "/images/placeholder.jpg",
                            Nombre = "Michi"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gata blanca muy mimosa",
                            Edad = 4,
                            Especie = 2,
                            Estado = 1,
                            Imagen = "/images/placeholder.jpg",
                            Nombre = "Nieve"
                        });
                });

            modelBuilder.Entity("AdopcionMascotas.Models.SolicitudAdopcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respuestas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("AdopcionMascotas.Models.SolicitudAdopcion", b =>
                {
                    b.HasOne("AdopcionMascotas.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
